services:
  postgres_db:
   image: postgres:18
   restart: always
   shm_size: 128mb
   volumes:
      - ./postgres-db-data/:/var/lib/postgresql/
   ports:
      - "5463:5432" 
   environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}